### ISSUE TITLE
Linux: Training and inference not working

### ISSUE THREAD

**Issue by Chilluminati91** [Mangio621/Mangio-RVC-Fork#1]
Its not possible to use the repo on linux atm (due to the different file path format?). This DOES work on the main RVC repo.

Output after clicking on "process data" in train tab:
```
python trainset_preprocess_pipeline_print.py /home/liam/Downloads/zro training/clips 40000 16 /home/liam/Mangio-RVC-Fork/logs/zro False
Traceback (most recent call last):
  File "/home/liam/Mangio-RVC-Fork/trainset_preprocess_pipeline_print.py", line 8, in <module>
    sr = int(sys.argv[2])
ValueError: invalid literal for int() with base 10: 'training/clips'
```
---

~~Another issue when trying inference (not sure if related):~~
```
loading weights/cabello.pth
gin_channels: 256 self.spk_embed_dim: 109
<All keys matched successfully>
Traceback (most recent call last):
  File "/home/liam/Mangio-RVC-Fork/my_utils.py", line 14, in load_audio
    ffmpeg.input(file, threads=0)
AttributeError: module 'ffmpeg' has no attribute 'input'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/liam/Mangio-RVC-Fork/infer-web.py", line 143, in vc_single
    audio = load_audio(input_audio, 16000)
  File "/home/liam/Mangio-RVC-Fork/my_utils.py", line 19, in load_audio
    raise RuntimeError(f"Failed to load audio: {e}")
RuntimeError: Failed to load audio: module 'ffmpeg' has no attribute 'input'

Traceback (most recent call last):
  File "/home/liam/Retrieval-based-Voice-Conversion-WebUI/venv/lib/python3.10/site-packages/gradio/routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/liam/Retrieval-based-Voice-Conversion-WebUI/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1111, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/home/liam/Retrieval-based-Voice-Conversion-WebUI/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1045, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/home/liam/Retrieval-based-Voice-Conversion-WebUI/venv/lib/python3.10/site-packages/gradio/components.py", line 2423, in postprocess
    processing_utils.audio_to_file(sample_rate, data, file.name)
  File "/home/liam/Retrieval-based-Voice-Conversion-WebUI/venv/lib/python3.10/site-packages/gradio/processing_utils.py", line 160, in audio_to_file
    data = convert_to_16_bit_wav(data)
  File "/home/liam/Retrieval-based-Voice-Conversion-WebUI/venv/lib/python3.10/site-packages/gradio/processing_utils.py", line 174, in convert_to_16_bit_wav
    if data.dtype in [np.float64, np.float32, np.float16]:
AttributeError: 'NoneType' object has no attribute 'dtype'
```

Second issue has been [fixed by manually](https://github.com/kkroening/ffmpeg-python/issues/174#issuecomment-561546739) removing ffmpeg and ffmpeg-python and reinstalling ffmpeg-python.

**Comment by Chilluminati91** [comment]
The first error is due to a space character in the file path. If I use a path without spaces it is working fine.
