### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by PureTuber** [Mangio621/Mangio-RVC-Fork#106]
I have an issue using the model. When I select a .pth file, this section gone error.
![image](https://github.com/Mangio621/Mangio-RVC-Fork/assets/117606892/73cbe41c-c51a-40f9-971b-7a31a76189e3)
>
![image](https://github.com/Mangio621/Mangio-RVC-Fork/assets/117606892/11ed77c9-b0de-4a03-9236-90a3646127f6)
How to fix it? Here is a code. 
`Found GPU NVIDIA GeForce GTX 650
Set fp16_run to false in 32k.json
Set fp16_run to false in 40k.json
Set fp16_run to false in 48k.json
Use Language: en_US
Running on local URL:  http://0.0.0.0:7897

To create a public link, set `share=True` in `launch()`.
loading weights/senjougahara.pth
gin_channels: 256 self.spk_embed_dim: 109
<All keys matched successfully>
Traceback (most recent call last):
  File "C:\Users\Tuber t\Desktop\Mangio-RVC-v23.7.0\runtime\lib\site-packages\gradio\routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Tuber t\Desktop\Mangio-RVC-v23.7.0\runtime\lib\site-packages\gradio\blocks.py", line 1346, in process_api
    result = await self.call_function(
  File "C:\Users\Tuber t\Desktop\Mangio-RVC-v23.7.0\runtime\lib\site-packages\gradio\blocks.py", line 1074, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\Tuber t\Desktop\Mangio-RVC-v23.7.0\runtime\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Tuber t\Desktop\Mangio-RVC-v23.7.0\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Tuber t\Desktop\Mangio-RVC-v23.7.0\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\Tuber t\Desktop\Mangio-RVC-v23.7.0\infer-web.py", line 589, in get_vc
    net_g = net_g.half()
  File "C:\Users\Tuber t\Desktop\Mangio-RVC-v23.7.0\runtime\lib\site-packages\torch\nn\modules\module.py", line 1001, in half
    return self._apply(lambda t: t.half() if t.is_floating_point() else t)
  File "C:\Users\Tuber t\Desktop\Mangio-RVC-v23.7.0\runtime\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Users\Tuber t\Desktop\Mangio-RVC-v23.7.0\runtime\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Users\Tuber t\Desktop\Mangio-RVC-v23.7.0\runtime\lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "C:\Users\Tuber t\Desktop\Mangio-RVC-v23.7.0\runtime\lib\site-packages\torch\nn\modules\module.py", line 1001, in <lambda>
    return self._apply(lambda t: t.half() if t.is_floating_point() else t)
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.`

**Comment by norasyeezys** [comment]
i have the same error after training 80 epoch
