### ISSUE TITLE
Training not working stopping after one epooch

### ISSUE THREAD

**Issue by ozmix** [Mangio621/Mangio-RVC-Fork#107]
Hi all I was using the previous one before this with easy GUI, and it worked.

I figured out how to allow easy GUI to work again thanks to the issues pages here to fix it

However now every time I use training this comes up after the first epoch

I am honestly not sure how to deal with it, this only happens with easy GUI too I can train just fine on go bat web

any ideas ?

Traceback (most recent call last):
  File "multiprocessing\process.py", line 315, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "F:\RVC\Mangio-RVC-v23.7.0\train_nsf_sim_cache_sid_load_pretrain.py", line 225, in run
    train_and_evaluate(
  File "F:\RVC\Mangio-RVC-v23.7.0\train_nsf_sim_cache_sid_load_pretrain.py", line 579, in train_and_evaluate
    cursor.execute("SELECT stop FROM stop_train LIMIT 1")
sqlite3.OperationalError: no such table: stop_train

**Comment by Skyf1re** [comment]
Hello! Try pasting these after "cursor = conn.corsor()" which on the 358 line:

```
cursor.execute('''
      CREATE TABLE IF NOT EXISTS stop_train (
        stop BOOL
      )
    ''')

    conn.commit()
```

It worked for me

**Comment by Aemeth21** [comment]
I had the same problem. I managed to fix it downloading and replacing 'train_nsf_sim_cache_sid_load_pretrain.py' file for the updated one. You can download the file here: https://github.com/Mangio621/Mangio-RVC-Fork/blob/main/train_nsf_sim_cache_sid_load_pretrain.py. The file you need to replace is found on the main Mangio RVC folder. Hope that helps :D
