### ISSUE TITLE
cant upload a file or download a model

### ISSUE THREAD

**Issue by RaMaNaN1970** [Mangio621/Mangio-RVC-Fork#132]
2023-09-17 12:14:00 | ERROR | root | Task exception was never retrieved
future: <Task finished name='h9p9xz62vnm_1' coro=<Queue.process_events() done, defined at H:\Mangio-RVC-v23.7.0_INFER\Mangio-RVC-v23.7.0\runtime\lib\site-packages\gradio\queueing.py:343> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [{'data': 'http:...on_hash': 'h9p9xz62vnm'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing>
Traceback (most recent call last):
  File "H:\Mangio-RVC-v23.7.0_INFER\Mangio-RVC-v23.7.0\runtime\lib\site-packages\gradio\queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "H:\Mangio-RVC-v23.7.0_INFER\Mangio-RVC-v23.7.0\runtime\lib\site-packages\gradio\queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "H:\Mangio-RVC-v23.7.0_INFER\Mangio-RVC-v23.7.0\runtime\lib\site-packages\gradio\queueing.py", line 456, in get_message
    return PredictBody(**data), True
  File "H:\Mangio-RVC-v23.7.0_INFER\Mangio-RVC-v23.7.0\runtime\lib\site-packages\pydantic\main.py", line 165, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [{'data': 'http:...on_hash': 'h9p9xz62vnm'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing

**Comment by Gitzillion** [comment]
hello, How did you fixed this Problem?, I am getting same problem.
