### ISSUE TITLE
queueing,gradio 

### ISSUE THREAD

**Issue by Gitzillion** [Mangio621/Mangio-RVC-Fork#134]
Queue Error, I cant Refresh or Upload, 

2023-09-18 08:05:31 | ERROR | root | Task exception was never retrieved
future: <Task finished name='yle1d8z9va_9' coro=<Queue.process_events() done, defined at D:\Newfolder\Mangio-RVC-v23.7.0\runtime\lib\site-packages\gradio\queueing.py:343> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [], 'event_data'...ion_hash': 'yle1d8z9va'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing>
Traceback (most recent call last):
  File "D:\Newfolder\Mangio-RVC-v23.7.0\runtime\lib\site-packages\gradio\queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "D:\Newfolder\Mangio-RVC-v23.7.0\runtime\lib\site-packages\gradio\queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "D:\Newfolder\Mangio-RVC-v23.7.0\runtime\lib\site-packages\gradio\queueing.py", line 456, in get_message
    return PredictBody(**data), True
  File "D:\Newfolder\Mangio-RVC-v23.7.0\runtime\lib\site-packages\pydantic\main.py", line 165, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [], 'event_data'...ion_hash': 'yle1d8z9va'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing

Please Help me to Solve This problem..
![Screenshot 2023-09-18 080842](https://github.com/Mangio621/Mangio-RVC-Fork/assets/145308414/3046f4ed-19db-4f6d-96bf-f6569e94541e)
![Screenshot 2023-09-18 080708](https://github.com/Mangio621/Mangio-RVC-Fork/assets/145308414/cce99268-9ce0-4e0a-af2a-b87feb5e3870)

**Comment by bascurtiz** [comment]
Seems I do have the same issue: 
![image](https://github.com/Mangio621/Mangio-RVC-Fork/assets/34075088/54ecf8f4-e304-41d5-b4db-45efc88f119e)

Happens when running easyGUI too, after selecting basically... anything.

However, I don't get verbal log:
![image](https://github.com/Mangio621/Mangio-RVC-Fork/assets/34075088/fe74dd3f-c7d2-43e1-a1db-86db2d22597c)

After I ctrl-alt-break the cmd, i get the same message however:
![image](https://github.com/Mangio621/Mangio-RVC-Fork/assets/34075088/8b344641-4fd0-402f-82c6-d77f7416bb38)

**Comment by bascurtiz** [comment]
All good after ditching all... and reinstall.
and following the advice of Random Bloke on the AI Hub: Don't use/install EasyGUI.

**Comment by Nawazsherif** [comment]
What steps you did without installing EasyGUI. @bascurtiz? Without running easygui script, i am getting few errors
