### ISSUE TITLE
Gradio queueing error

### ISSUE THREAD

**Issue by equmaq** [Mangio621/Mangio-RVC-Fork#135]
When trying to process audio for training, these error messages show up

`2023-09-18 18:13:47 | ERROR | root | Task exception was never retrieved
future: <Task finished name='pj52cltwyao_21' coro=<Queue.process_events() done, defined at F:\AI_voice_suff\Mangio-RVC-v23.7.0\runtime\lib\site-packages\gradio\queueing.py:343> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [[{'data': 'http...on_hash': 'pj52cltwyao'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing>
Traceback (most recent call last):
  File "F:\AI_voice_suff\Mangio-RVC-v23.7.0\runtime\lib\site-packages\gradio\queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "F:\AI_voice_suff\Mangio-RVC-v23.7.0\runtime\lib\site-packages\gradio\queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "F:\AI_voice_suff\Mangio-RVC-v23.7.0\runtime\lib\site-packages\gradio\queueing.py", line 456, in get_message
    return PredictBody(**data), True
  File "F:\AI_voice_suff\Mangio-RVC-v23.7.0\runtime\lib\site-packages\pydantic\main.py", line 165, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [[{'data': 'http...on_hash': 'pj52cltwyao'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
2023-09-18 18:13:54 | ERROR | root | Task exception was never retrieved
future: <Task finished name='pj52cltwyao_22' coro=<Queue.process_events() done, defined at F:\AI_voice_suff\Mangio-RVC-v23.7.0\runtime\lib\site-packages\gradio\queueing.py:343> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': ['./dataset', 'S...on_hash': 'pj52cltwyao'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing>
Traceback (most recent call last):
  File "F:\AI_voice_suff\Mangio-RVC-v23.7.0\runtime\lib\site-packages\gradio\queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "F:\AI_voice_suff\Mangio-RVC-v23.7.0\runtime\lib\site-packages\gradio\queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "F:\AI_voice_suff\Mangio-RVC-v23.7.0\runtime\lib\site-packages\gradio\queueing.py", line 456, in get_message
    return PredictBody(**data), True
  File "F:\AI_voice_suff\Mangio-RVC-v23.7.0\runtime\lib\site-packages\pydantic\main.py", line 165, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': ['./dataset', 'S...on_hash': 'pj52cltwyao'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
2023-09-18 18:17:30 | ERROR | root | Task exception was never retrieved
future: <Task finished name='qb1tlfxif7e_21' coro=<Queue.process_events() done, defined at F:\AI_voice_suff\Mangio-RVC-v23.7.0\runtime\lib\site-packages\gradio\queueing.py:343> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [[{'data': 'http...on_hash': 'qb1tlfxif7e'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing>
Traceback (most recent call last):
  File "F:\AI_voice_suff\Mangio-RVC-v23.7.0\runtime\lib\site-packages\gradio\queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "F:\AI_voice_suff\Mangio-RVC-v23.7.0\runtime\lib\site-packages\gradio\queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "F:\AI_voice_suff\Mangio-RVC-v23.7.0\runtime\lib\site-packages\gradio\queueing.py", line 456, in get_message
    return PredictBody(**data), True
  File "F:\AI_voice_suff\Mangio-RVC-v23.7.0\runtime\lib\site-packages\pydantic\main.py", line 165, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [[{'data': 'http...on_hash': 'qb1tlfxif7e'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing`

**Comment by AkterAhsan** [comment]
Same Here.

ERROR | root | Task exception was never retrieved
future: <Task finished name='4f44fuxcdl9_7' coro=<Queue.process_events() done, defined at C:\ai\rvc\runtime\lib\site-packages\gradio\queueing.py:343> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [], 'event_data'...on_hash': '4f44fuxcdl9'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.4/v/missing>
Traceback (most recent call last):
  File "C:\ai\rvc\runtime\lib\site-packages\gradio\queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "C:\ai\rvc\runtime\lib\site-packages\gradio\queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "C:\ai\rvc\runtime\lib\site-packages\gradio\queueing.py", line 456, in get_message
    return PredictBody(**data), True
  File "C:\ai\rvc\runtime\lib\site-packages\pydantic\main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [], 'event_data'...on_hash': '4f44fuxcdl9'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.4/v/missing

**Comment by dejl** [comment]
I get the same issue. has anyone fixed?

**Comment by temir-erd** [comment]
I get the same issue.

**Comment by essovius** [comment]
i'm getting the same error. any fixes?
