### ISSUE TITLE
Training process failed because of ffmpeg error

### ISSUE THREAD

**Issue by Senkanoko** [Mangio621/Mangio-RVC-Fork#145]
start preprocess
['trainset_preprocess_pipeline_print.py', 'C:\\Users\\ledin\\Documents\\Mangio-RVC-v23.7.0\\datasets\\', '40000', '8', 'C:\\Users\\ledin\\Documents\\Mangio-RVC-v23.7.0/logs/mi-test', 'False']
C:\Users\ledin\Documents\Mangio-RVC-v23.7.0\datasets\/meow->Traceback (most recent call last):
  File "C:\Users\ledin\Documents\Mangio-RVC-v23.7.0\my_utils.py", line 96, in load_audio
    ffmpeg.input(file, threads=0)
  File "C:\Users\ledin\Documents\Mangio-RVC-v23.7.0\runtime\lib\site-packages\ffmpeg\_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ledin\Documents\Mangio-RVC-v23.7.0\trainset_preprocess_pipeline_print.py", line 84, in pipeline
    audio = load_audio(path, self.sr, DoFormant, Quefrency, Timbre)
  File "C:\Users\ledin\Documents\Mangio-RVC-v23.7.0\my_utils.py", line 103, in load_audio
    raise RuntimeError(f"Failed to load audio: {e}")
RuntimeError: Failed to load audio: ffmpeg error (see stderr output for detail)

end preprocess

What should I do now?

**Comment by MRINFINITE0** [comment]
hey, do you get any solution for this issue?
and also can you tell me the differance between mangio fork rvc and rvc from notebook

**Comment by Senkanoko** [comment]
I found the problem, thanks

**Comment by yuzulite** [comment]
What was the fix? I'm getting the same error. I saw in the FAQ its an audio path issue but I'm not sure what that means.

I've already tried uninstalling and installing ffmpeg again

**Comment by xjax9012** [comment]
I had the same issue and managed to get past it by modifying the `trainset_preprocess_pipeline_print.py` file. 
I was looking for a solution everywhere and someone [here](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/issues/711) suggested this fix. I did it and the ffmpeg error was gone but I got another one (some missing attributes) so I tried tweaking the file on my own and it seemingly worked. Not sure how it exactly turned out because I had other (most likely unrelated) errors later on and didn't get to finish training the model but the data was apparently processed successfully so I think it should solve this particular issue.  
I'll leave the code below in case anyone wants to try it out but **make sure to back up the original file** as I'm not an expert and I'm not sure if it will work for you.

Here's the final version:
```python
import sys, os, multiprocessing
from scipy import signal
import scipy

now_dir = os.getcwd()
sys.path.append(now_dir)

inp_root = sys.argv[1]
sr = int(sys.argv[2])
n_p = int(sys.argv[3])
exp_dir = sys.argv[4]
noparallel = sys.argv[5] == "True"
import numpy as np, os, traceback
from slicer2 import Slicer
import librosa
from scipy.io import wavfile
from my_utils import load_audio

DoFormant = False
Quefrency = 0.0
Timbre = 0.0

mutex = multiprocessing.Lock()

def println(strr):
    with open("%s/preprocess.log" % exp_dir, "a+") as f:
        mutex.acquire()
        print(strr)
        f.write("%s\n" % strr)
        f.flush()
        mutex.release()


class PreProcess:
    def __init__(self, sr, exp_dir):
        self.slicer = Slicer(
            sr=sr,
            threshold=-42,
            min_length=1500,
            min_interval=400,
            hop_size=15,
            max_sil_kept=500,
        )
        self.sr = sr
        self.bh, self.ah = signal.butter(N=5, Wn=48, btype="high", fs=self.sr)
        self.per = 3.7
        self.overlap = 0.3
        self.tail = self.per + self.overlap
        self.max = 0.9
        self.alpha = 0.75
        self.exp_dir = exp_dir
        self.gt_wavs_dir = "%s/0_gt_wavs" % exp_dir
        self.wavs16k_dir = "%s/1_16k_wavs" % exp_dir
        os.makedirs(self.exp_dir, exist_ok=True)
        os.makedirs(self.gt_wavs_dir, exist_ok=True)
        os.makedirs(self.wavs16k_dir, exist_ok=True)

    def norm_write(self, tmp_audio, idx0, idx1):
        tmp_max = np.abs(tmp_audio).max()
        if tmp_max > 2.5:
            print("%s-%s-%s-filtered" % (idx0, idx1, tmp_max))
            return
        tmp_audio = (tmp_audio / tmp_max * (self.max * self.alpha)) + (
            1 - self.alpha
        ) * tmp_audio
        wavfile.write(
            "%s/%s_%s.wav" % (self.gt_wavs_dir, idx0, idx1),
            self.sr,
            tmp_audio.astype(np.float32),
        )
        tmp_audio_resampled = librosa.resample(tmp_audio, orig_sr=self.sr, target_sr=16000)
        wavfile.write(
            "%s/%s_%s.wav" % (self.wavs16k_dir, idx0, idx1),
            16000,
            tmp_audio_resampled.astype(np.float32),
        )


    def pipeline(self, path, idx0):
        try:
            audio = load_audio(path, self.sr, DoFormant, Quefrency, Timbre)
            # zero phased digital filter cause pre-ringing noise...
            # audio = signal.filtfilt(self.bh, self.ah, audio)
            audio = signal.lfilter(self.bh, self.ah, audio)

            idx1 = 0
            for audio in self.slicer.slice(audio):
                i = 0
                while 1:
                    start = int(self.sr * (self.per - self.overlap) * i)
                    i += 1
                    if len(audio[start:]) > self.tail * self.sr:
                        tmp_audio = audio[start : start + int(self.per * self.sr)]
                        self.norm_write(tmp_audio, idx0, idx1)
                        idx1 += 1
                    else:
                        tmp_audio = audio[start:]
                        idx1 += 1
                        break
                self.norm_write(tmp_audio, idx0, idx1)
            println("%s->Suc." % path)
        except:
            println("%s->%s" % (path, traceback.format_exc()))

    def pipeline_mp(self, infos):
        for path, idx0 in infos:
            self.pipeline(path, idx0)

    def pipeline_mp_inp_dir(self, inp_root, n_p):
        try:
            file_extensions = [".wav"]  # Add other audio file extensions as needed
            infos = [
                ("%s/%s" % (inp_root, name), idx)
                for idx, name in enumerate(sorted(list(os.listdir(inp_root))))
                if os.path.splitext(name)[1] in file_extensions
            ]
            if noparallel:
                for i in range(n_p):
                    self.pipeline_mp(infos[i::n_p])
            else:
                ps = []
                for i in range(n_p):
                    p = multiprocessing.Process(
                        target=self.pipeline_mp, args=(infos[i::n_p],)
                    )
                    ps.append(p)
                    p.start()
                for i in range(n_p):
                    ps[i].join()
        except:
            println("Fail. %s" % traceback.format_exc())



def preprocess_trainset(inp_root, sr, n_p, exp_dir):
    pp = PreProcess(sr, exp_dir)
    println("start preprocess")
    println(sys.argv)
    pp.pipeline_mp_inp_dir(inp_root, n_p)
    println("end preprocess")


if __name__ == "__main__":
    preprocess_trainset(inp_root, sr, n_p, exp_dir)
``` 

Also make sure you put .wav files in there and that their names don't contain any special characters because apparently this may also cause this error.

**Comment by vivekjvsdot** [comment]
I got the same error while working with RVC-WebUI.
Upon investigation,I found that there are hidden files in the audio(training dataset) directory.I named it as 'work'
In my case,there were ".DS_Store" files.
The ".DS_Store" file is a system file created by macOS Finder to store custom attributes of a folder. It's not an audio file, so attempting to load it as audio is causing the error.

to delete the files(macos)
`find . -name ".DS_Store" -print -delete
 `

<img width="909" alt="image" src="https://github.com/Mangio621/Mangio-RVC-Fork/assets/74709571/92bfc160-2e5e-4b8a-8d62-1067d16a14c5">
The error is resolved.Hope it helps you.
