### ISSUE TITLE
the output takes forever... no output was generated :(

### ISSUE THREAD

**Issue by ruu-u** [Mangio621/Mangio-RVC-Fork#146]
I'm doing it locally becoz I cannot even launch RVC on the google colab.
I think I run though everything but the output seems to take forever to load... so Im kinda stuck here (refer to the screenshot below) I've been waiting for like 1hr atm, (if its normal to take this long it might sound stupid but I cant find the average time it takes... ) is there any way to solve this?

<img width="1512" alt="Screenshot 2023-10-07 at 01 35 47" src="https://github.com/Mangio621/Mangio-RVC-Fork/assets/147191080/2804e617-5054-4076-b401-cc86655477aa">

Originally it cannot load the audio file either when I drag the file in, I end up putting the audio file inside the folder "audio", so that it appears in the drop down menu at 2. choose your audio, is this correct to do so?

**Comment by owovin** [comment]
getting similar effect when hosting local, no logs are genned, it acts like it stalls. The voice changer works, but any of the gradio guis  (v1 and v2) do it.
You are doing everything correct, i just dont know whats wrong

**Comment by thedfer** [comment]
I have been facing the exact same problem and this is my attempt with RVC. I had manually upload the .pth and .index and the audios files to respective folders for th web UI to recognize them because none of the UI buttons were doing the job and taking forever to upload model or audio file. Now after I manually loaded the files and finally hit convert, I face the same problem of running the convert task forever. 
The problem is not only with EasyGUI. The generic go-web UI also doing the same thing. None of the buttons are doing what they are suppose to do. Instead they just run forever.
I don't know if there is any solution to this problem. Any help is appreciated.

**Comment by JackTheFroster** [comment]
The first time i was running it locally, i had other problems, i think it was only with training tho, but the convert process worked without any issues. after deleting everything, because i thought i might encounter less problems with the colab, and downloading the local files again, i encounter the same problem. cmd says:

2023-11-02 01:30:18 | ERROR | root | Task exception was never retrieved
future: <Task finished name='j3mz9tazxth_9' coro=<Queue.process_events() done, defined at C:\Users\Dionsaurier\Music\RVC\runtime\lib\site-packages\gradio\queueing.py:343> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [], 'event_data'...on_hash': 'j3mz9tazxth'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.4/v/missing>
Traceback (most recent call last):
  File "C:\Users\Dionsaurier\Music\RVC\runtime\lib\site-packages\gradio\queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "C:\Users\Dionsaurier\Music\RVC\runtime\lib\site-packages\gradio\queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "C:\Users\Dionsaurier\Music\RVC\runtime\lib\site-packages\gradio\queueing.py", line 456, in get_message
    return PredictBody(**data), True
  File "C:\Users\Dionsaurier\Music\RVC\runtime\lib\site-packages\pydantic\main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [], 'event_data'...on_hash': 'j3mz9tazxth'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.4/v/missing

Edit: actually downloading the whole package from the .bat, extracting ONLY the \runtime\lib\site-packages\pydantic\ folder and replacing it with the existing one fixed this for me

**Comment by ForcedComedy** [comment]
is no one else having the same issue? i get no errors while launching, none whatsoever. yet nothing works. trying to download models, refreshing audio lists, refreshing models, trying to get an output. everything just gets stuck in queue infinitely.

**Comment by Mixomo** [comment]
> The first time i was running it locally, i had other problems, i think it was only with training tho, but the convert process worked without any issues. after deleting everything, because i thought i might encounter less problems with the colab, and downloading the local files again, i encounter the same problem. cmd says:
> 
> 2023-11-02 01:30:18 | ERROR | root | Task exception was never retrieved future: <Task finished name='j3mz9tazxth_9' coro=<Queue.process_events() done, defined at C:\Users\Dionsaurier\Music\RVC\runtime\lib\site-packages\gradio\queueing.py:343> exception=1 validation error for PredictBody event_id Field required [type=missing, input_value={'data': [], 'event_data'...on_hash': 'j3mz9tazxth'}, input_type=dict] For further information visit [https://errors.pydantic.dev/2.4/v/missing>](https://errors.pydantic.dev/2.4/v/missing%3E) Traceback (most recent call last): File "C:\Users\Dionsaurier\Music\RVC\runtime\lib\site-packages\gradio\queueing.py", line 347, in process_events client_awake = await self.gather_event_data(event) File "C:\Users\Dionsaurier\Music\RVC\runtime\lib\site-packages\gradio\queueing.py", line 220, in gather_event_data data, client_awake = await self.get_message(event, timeout=receive_timeout) File "C:\Users\Dionsaurier\Music\RVC\runtime\lib\site-packages\gradio\queueing.py", line 456, in get_message return PredictBody(**data), True File "C:\Users\Dionsaurier\Music\RVC\runtime\lib\site-packages\pydantic\main.py", line 164, in **init** **pydantic_self**.**pydantic_validator**.validate_python(data, self_instance=**pydantic_self**) pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody event_id Field required [type=missing, input_value={'data': [], 'event_data'...on_hash': 'j3mz9tazxth'}, input_type=dict] For further information visit https://errors.pydantic.dev/2.4/v/missing
> 
> Edit: actually downloading the whole package from the .bat, extracting ONLY the \runtime\lib\site-packages\pydantic\ folder and replacing it with the existing one fixed this for me

IT'S WORKED! Thank you!

**Comment by JaspreetDev** [comment]
> > The first time i was running it locally, i had other problems, i think it was only with training tho, but the convert process worked without any issues. after deleting everything, because i thought i might encounter less problems with the colab, and downloading the local files again, i encounter the same problem. cmd says:
> > 2023-11-02 01:30:18 | ERROR | root | Task exception was never retrieved future: <Task finished name='j3mz9tazxth_9' coro=<Queue.process_events() done, defined at C:\Users\Dionsaurier\Music\RVC\runtime\lib\site-packages\gradio\queueing.py:343> exception=1 validation error for PredictBody event_id Field required [type=missing, input_value={'data': [], 'event_data'...on_hash': 'j3mz9tazxth'}, input_type=dict] For further information visit [https://errors.pydantic.dev/2.4/v/missing>](https://errors.pydantic.dev/2.4/v/missing%3E) Traceback (most recent call last): File "C:\Users\Dionsaurier\Music\RVC\runtime\lib\site-packages\gradio\queueing.py", line 347, in process_events client_awake = await self.gather_event_data(event) File "C:\Users\Dionsaurier\Music\RVC\runtime\lib\site-packages\gradio\queueing.py", line 220, in gather_event_data data, client_awake = await self.get_message(event, timeout=receive_timeout) File "C:\Users\Dionsaurier\Music\RVC\runtime\lib\site-packages\gradio\queueing.py", line 456, in get_message return PredictBody(**data), True File "C:\Users\Dionsaurier\Music\RVC\runtime\lib\site-packages\pydantic\main.py", line 164, in **init** **pydantic_self**.**pydantic_validator**.validate_python(data, self_instance=**pydantic_self**) pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody event_id Field required [type=missing, input_value={'data': [], 'event_data'...on_hash': 'j3mz9tazxth'}, input_type=dict] For further information visit https://errors.pydantic.dev/2.4/v/missing
> > Edit: actually downloading the whole package from the .bat, extracting ONLY the \runtime\lib\site-packages\pydantic\ folder and replacing it with the existing one fixed this for me
> 
> IT'S WORKED! Thank you!

Could you explain the details? It's unclear from the comment above what files are supposed to replace the original. I'm trying to run it locally.

**Comment by JackTheFroster** [comment]
My guess is, that the "INSTALL_Mangio-RVC-v23.7.0_INFER.bat" on this fork actually downloads a different package than the huggingface "Mangio-RVC-v23.7.0_INFER.7z" package. The only difference i am seeing, is the link. The .bat is referring to "https://huggingface.co/MangioRVC/Mangio-RVC-Huggingface/resolve/main/Mangio-RVC-v23.7.0_INFER.7z" and the other link is "https://huggingface.co/MangioRVC/Mangio-RVC-Huggingface/blob/main/Mangio-RVC-v23.7.0_INFER.7z" where the only difference is the "resolve" and "blob" part. Anyways, it would make no sense for me that there is a difference in the package, but for whatever reason, downloading from the .bat on this fork (with or without "TRAIN"), ends without any issues. Meaning if you downloaded directly from the huggingface website, try and download the package again from the .bat file. When you already changed any files from the already unzipped package, the possibility, when facing the same "never ending loading" issue, is there, that some files in the *RVC directory*\runtime\lib\site-packages\pydantic\ folder are corrupted. Either they got corrupted in the time, meaning the huggingface "blob" package is not even any different from the "resolve" package, or the "blob" package is actually containing a corrupted "pydantic" folder. After all this information, a quicker explaination for fixing this problem *hopefully*:

DISCLAIMER: If i mention "package", i mean the whole files from the ".7z" file (2.55GB or 4.7GB with "_TRAIN")
If you manage to still have the unzipped NOT working package, follow the steps. If you have DELETED every not working package, you can just download the package from step 1 and extract all folders and files to a safe place. If the same error is happening again after unzipping everything freshly new, try following these steps anyways.

1. Re-download the preferred version from this fork: "https://github.com/Mangio621/Mangio-RVC-Fork/releases". Choose either the one with "_TRAIN" at the end, when you want to train models, or the one without "_TRAIN", if you do not want to train models. Run the downloaded ".bat" so it downloads the ".7z" package for you.
2. After the package was successfully downloaded, open the ".7z" file and ONLY open the directory: "*RVC directory with many files*\runtime\lib\site-packages\". There should be plenty folders. ONLY search for the "pydantic" folder, nothing else behind it, and extract it somewhere safe.
3. Now, go to the already unzipped and not working package and locate the "pydantic" folder again in "\runtime\lib\site-packages\". Delete it and move the newer unzipped "pydantic" folder from step 2 in there.
4. Go back to the main RVC directory and try running "go-web.bat" and train a model, OR try "install_easyGUI.bat", wait until it is finished and open "run_easiergui.bat" and convert any audio with an existing model.

Hope this helped!

**Comment by chille9** [comment]
The above steps by jack was the ONLY solution i found after three hours of trying things.

1. The issue for the easy gui and things being broken is the pydantic folder in files\runtime\lib\site-packages. 

2. When you start any gui the software messes up these files. So reset them by dragging in the pydantic folder AGAIN from the downloaded "install.7z" after booting once, 

3. As for the easy gui you need this file also: my_utils.py from kalos tweaks.
https://github.com/kalomaze/Mangio-Kalo-Tweaks/blob/main/my_utils.py

Yo please make this a sticky in the install notes of this project. Its embarrassing to have to look for these "work-arounds" with a fresh install that isnt working.
