### ISSUE TITLE
Error when trying to inferfence

### ISSUE THREAD

**Issue by Chris2918** [Mangio621/Mangio-RVC-Fork#15]
When I press "Convert", I get this error:
Traceback (most recent call last):
  File "C:\Users\lccji\Downloads\Mangio-RVC-Fork-main\my_utils.py", line 14, in load_audio
    ffmpeg.input(file, threads=0)
AttributeError: module 'ffmpeg' has no attribute 'input'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lccji\Downloads\Mangio-RVC-Fork-main\infer-web.py", line 163, in vc_single
    audio = load_audio(input_audio_path, 16000)
  File "C:\Users\lccji\Downloads\Mangio-RVC-Fork-main\my_utils.py", line 19, in load_audio
    raise RuntimeError(f"Failed to load audio: {e}")
RuntimeError: Failed to load audio: module 'ffmpeg' has no attribute 'input'

Traceback (most recent call last):
  File "C:\Users\lccji\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\lccji\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1349, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\lccji\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1283, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\Users\lccji\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\components.py", line 2586, in postprocess
    file_path = self.audio_to_temp_file(
  File "C:\Users\lccji\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\components.py", line 360, in audio_to_temp_file
    temp_dir = Path(dir) / self.hash_bytes(data.tobytes())
AttributeError: 'NoneType' object has no attribute 'tobytes'

**Comment by LollenApe** [comment]
hi, i have the same kind of problem, did you solve it?

**Comment by hamzagorgulu** [comment]
same here

**Comment by LollenApe** [comment]
i think i found the problem: is a gradio issue, try installing gradio==3.34.0

**Comment by NotSkynet** [comment]
I'm guessing this happens if you've installed both, ffmpeg and ffmpeg-python.
uninstall both with:
pip uninstall ffmpeg
pip uninstall ffmpeg-python
for good measure uninstall ffmpy along with these two so
pip uninstall ffmpy

and install ffmpeg-python and ffmpy again with :
pip install ffmpeg-python
pip install ffmpy

This solved the problem in my system :)

**Comment by yuzulite** [comment]
> I'm guessing this happens if you've installed both, ffmpeg and ffmpeg-python. uninstall both with: pip uninstall ffmpeg pip uninstall ffmpeg-python for good measure uninstall ffmpy along with these two so: pip uninstall ffmpy
> 
> and install ffmpeg-python and ffmpy again with : pip install ffmpeg-python pip install ffmpy
> 
> This solved the problem in my system :)

How exactly do I uninstall and reinstall in Mangio? I'm new to this so I'm not sure sorry.

**Comment by LollenApe** [comment]
> > I'm guessing this happens if you've installed both, ffmpeg and ffmpeg-python. uninstall both with: pip uninstall ffmpeg pip uninstall ffmpeg-python for good measure uninstall ffmpy along with these two so: pip uninstall ffmpy
> > and install ffmpeg-python and ffmpy again with : pip install ffmpeg-python pip install ffmpy
> > This solved the problem in my system :)
> 
> How exactly do I uninstall and reinstall in Mangio? I'm new to this so I'm not sure sorry.

he literally said the commands for it, do it on the terminal
