### ISSUE TITLE
NameError: name 'easy_uploader' is not defined

### ISSUE THREAD

**Issue by Dhrhciebcy** [Mangio621/Mangio-RVC-Fork#153]
Traceback (most recent call last):
  File "D:\RVC-V2\Mangio-RVC-v23.7.0\runtime\lib\site-packages\gradio\routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\RVC-V2\Mangio-RVC-v23.7.0\runtime\lib\site-packages\gradio\blocks.py", line 1346, in process_api
    result = await self.call_function(
  File "D:\RVC-V2\Mangio-RVC-v23.7.0\runtime\lib\site-packages\gradio\blocks.py", line 1074, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\RVC-V2\Mangio-RVC-v23.7.0\runtime\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\RVC-V2\Mangio-RVC-v23.7.0\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\RVC-V2\Mangio-RVC-v23.7.0\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\RVC-V2\Mangio-RVC-v23.7.0\EasierGUI.py", line 1825, in <lambda>
    but1.click(fn=lambda: easy_uploader.clear())
NameError: name 'easy_uploader' is not defined

I am using EasierGUI, all seems ok until I press generate button, then this error appears. Any ideas?

**Comment by Dhrhciebcy** [comment]
I eventually discovered that I was pressing the wrong button, the generate I pressed was under the Batch Conversion section
