### ISSUE TITLE
Error when training locally

### ISSUE THREAD

**Issue by deadpassion** [Mangio621/Mangio-RVC-Fork#155]
Everything's fine up to the actual training point, but the cmd throws some error and I don't get my pth and index files. 

```
write filelist done
use gpus: 0
runtime\python.exe train_nsf_sim_cache_sid_load_pretrain.py -e vera2 -sr 40k -f0 1 -bs 4 -g 0 -te 100 -se 10 -pg pretrained/f0G40k.pth -pd pretrained/f0D40k.pth -l 1 -c 0 -sw 1 -v v1 -li 6
INFO:vera2:{'train': {'log_interval': 6, 'seed': 1234, 'epochs': 20000, 'learning_rate': 0.0001, 'betas': [0.8, 0.99], 'eps': 1e-09, 'batch_size': 4, 'fp16_run': True, 'lr_decay': 0.999875, 'segment_size': 12800, 'init_lr_ratio': 1, 'warmup_epochs': 0, 'c_mel': 45, 'c_kl': 1.0}, 'data': {'max_wav_value': 32768.0, 'sampling_rate': 40000, 'filter_length': 2048, 'hop_length': 400, 'win_length': 2048, 'n_mel_channels': 125, 'mel_fmin': 0.0, 'mel_fmax': None, 'training_files': './logs\\vera2/filelist.txt'}, 'model': {'inter_channels': 192, 'hidden_channels': 192, 'filter_channels': 768, 'n_heads': 2, 'n_layers': 6, 'kernel_size': 3, 'p_dropout': 0, 'resblock': '1', 'resblock_kernel_sizes': [3, 7, 11], 'resblock_dilation_sizes': [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 'upsample_rates': [10, 10, 2, 2], 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [16, 16, 4, 4], 'use_spectral_norm': False, 'gin_channels': 256, 'spk_embed_dim': 109}, 'model_dir': './logs\\vera2', 'experiment_dir': './logs\\vera2', 'save_every_epoch': 10, 'name': 'vera2', 'total_epoch': 100, 'pretrainG': 'pretrained/f0G40k.pth', 'pretrainD': 'pretrained/f0D40k.pth', 'version': 'v1', 'gpus': '0', 'sample_rate': '40k', 'if_f0': 1, 'if_latest': 1, 'save_every_weights': '1', 'if_cache_data_in_gpu': 0}
INFO:torch.distributed.distributed_c10d:Added key: store_based_barrier_key:1 to store for rank: 0
INFO:torch.distributed.distributed_c10d:Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 1 nodes.
gin_channels: 256 self.spk_embed_dim: 109
INFO:vera2:loaded pretrained pretrained/f0G40k.pth
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\Mihael\Desktop\rvc\Mangio-RVC-v23.7.0\train_nsf_sim_cache_sid_load_pretrain.py", line 181, in run
    utils.latest_checkpoint_path(hps.model_dir, "D_*.pth"), net_d, optim_d
  File "C:\Users\Mihael\Desktop\rvc\Mangio-RVC-v23.7.0\train\utils.py", line 206, in latest_checkpoint_path
    x = f_list[-1]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "multiprocessing\process.py", line 315, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "C:\Users\Mihael\Desktop\rvc\Mangio-RVC-v23.7.0\train_nsf_sim_cache_sid_load_pretrain.py", line 201, in run
    torch.load(hps.pretrainG, map_location="cpu")["model"]
  File "C:\Users\Mihael\Desktop\rvc\Mangio-RVC-v23.7.0\runtime\lib\site-packages\torch\serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\Mihael\Desktop\rvc\Mangio-RVC-v23.7.0\runtime\lib\site-packages\torch\serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\Mihael\Desktop\rvc\Mangio-RVC-v23.7.0\runtime\lib\site-packages\torch\serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'pretrained/f0G40k.pth'
```

This is my train log also:

```
2023-10-29 17:18:30,072	vera2	INFO	{'train': {'log_interval': 6, 'seed': 1234, 'epochs': 20000, 'learning_rate': 0.0001, 'betas': [0.8, 0.99], 'eps': 1e-09, 'batch_size': 4, 'fp16_run': True, 'lr_decay': 0.999875, 'segment_size': 12800, 'init_lr_ratio': 1, 'warmup_epochs': 0, 'c_mel': 45, 'c_kl': 1.0}, 'data': {'max_wav_value': 32768.0, 'sampling_rate': 40000, 'filter_length': 2048, 'hop_length': 400, 'win_length': 2048, 'n_mel_channels': 125, 'mel_fmin': 0.0, 'mel_fmax': None, 'training_files': './logs\\vera2/filelist.txt'}, 'model': {'inter_channels': 192, 'hidden_channels': 192, 'filter_channels': 768, 'n_heads': 2, 'n_layers': 6, 'kernel_size': 3, 'p_dropout': 0, 'resblock': '1', 'resblock_kernel_sizes': [3, 7, 11], 'resblock_dilation_sizes': [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 'upsample_rates': [10, 10, 2, 2], 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [16, 16, 4, 4], 'use_spectral_norm': False, 'gin_channels': 256, 'spk_embed_dim': 109}, 'model_dir': './logs\\vera2', 'experiment_dir': './logs\\vera2', 'save_every_epoch': 10, 'name': 'vera2', 'total_epoch': 100, 'pretrainG': 'pretrained/f0G40k.pth', 'pretrainD': 'pretrained/f0D40k.pth', 'version': 'v1', 'gpus': '0', 'sample_rate': '40k', 'if_f0': 1, 'if_latest': 1, 'save_every_weights': '1', 'if_cache_data_in_gpu': 0}
2023-10-29 17:18:31,816	vera2	INFO	loaded pretrained pretrained/f0G40k.pth
```

**Comment by vysecurity** [comment]
I am having the same issue. Any luck?
