### ISSUE TITLE
im trying to separate vocals but when i click convert:

### ISSUE THREAD

**Issue by Abdelkher** [Mangio621/Mangio-RVC-Fork#166]
MARWAN MOUSSA - BATAL 3ALAM OFFICIAL MUSIC VIDEO مروان موسى - بطل عالم --MP3_320K.mp3.reformatted.wav->Traceback (most recent call last):
  File "D:\rvc\Mangio-RVC-v23.7.0_INFER_TRAIN\Mangio-RVC-v23.7.0\runtime\lib\site-packages\librosa\core\audio.py", line 155, in load
    context = sf.SoundFile(path)
  File "D:\rvc\Mangio-RVC-v23.7.0_INFER_TRAIN\Mangio-RVC-v23.7.0\runtime\lib\site-packages\soundfile.py", line 658, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "D:\rvc\Mangio-RVC-v23.7.0_INFER_TRAIN\Mangio-RVC-v23.7.0\runtime\lib\site-packages\soundfile.py", line 1216, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening 'D:\\rvc\\Mangio-RVC-v23.7.0_INFER_TRAIN\\Mangio-RVC-v23.7.0\\TEMP/MARWAN MOUSSA - BATAL 3ALAM OFFICIAL MUSIC VIDEO مروان موسى - بطل عالم --MP3_320K.mp3.reformatted.wav': System error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\rvc\Mangio-RVC-v23.7.0_INFER_TRAIN\Mangio-RVC-v23.7.0\infer-web.py", line 489, in uvr
    pre_fun._path_audio_(
  File "D:\rvc\Mangio-RVC-v23.7.0_INFER_TRAIN\Mangio-RVC-v23.7.0\infer_uvr5.py", line 64, in _path_audio_
    ) = librosa.core.load(  # 理论上librosa读取可能对某些音频有bug，应该上ffmpeg读取，但是太麻烦了弃坑
  File "D:\rvc\Mangio-RVC-v23.7.0_INFER_TRAIN\Mangio-RVC-v23.7.0\runtime\lib\site-packages\librosa\util\decorators.py", line 104, in inner_f
    return f(**kwargs)
  File "D:\rvc\Mangio-RVC-v23.7.0_INFER_TRAIN\Mangio-RVC-v23.7.0\runtime\lib\site-packages\librosa\core\audio.py", line 174, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "D:\rvc\Mangio-RVC-v23.7.0_INFER_TRAIN\Mangio-RVC-v23.7.0\runtime\lib\site-packages\librosa\core\audio.py", line 198, in __audioread_load
    with audioread.audio_open(path) as input_file:
  File "D:\rvc\Mangio-RVC-v23.7.0_INFER_TRAIN\Mangio-RVC-v23.7.0\runtime\lib\site-packages\audioread\__init__.py", line 127, in audio_open
    return BackendClass(path)
  File "D:\rvc\Mangio-RVC-v23.7.0_INFER_TRAIN\Mangio-RVC-v23.7.0\runtime\lib\site-packages\audioread\rawread.py", line 59, in __init__
    self._fh = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\rvc\\Mangio-RVC-v23.7.0_INFER_TRAIN\\Mangio-RVC-v23.7.0\\TEMP/MARWAN MOUSSA - BATAL 3ALAM OFFICIAL MUSIC VIDEO مروان موسى - بطل عالم --MP3_320K.mp3.reformatted.wav'

**Comment by TheYellowArchitect** [comment]
Aside of the non-english title,  it's probably because of the file suffix ".mp3.reformatted.wav"
It should be pure .wav, instead of renaming it to .wav
