### ISSUE TITLE
Failed to run in Mac mini m2

### ISSUE THREAD

**Issue by zhouhao27** [Mangio621/Mangio-RVC-Fork#198]
I followed the instruction and download the MacOS_Onlyxxx zip file and upzip it. Then in this folder, I run `run.sh`.  Got the following error message:

> Traceback (most recent call last):
  File "infer-web.py", line 30, in <module>
    from fairseq import checkpoint_utils
  File "/Users/user/miniconda3/envs/rvc/lib/python3.8/site-packages/fairseq/__init__.py", line 40, in <module>
    import fairseq.scoring  # noqa
  File "/Users/user/miniconda3/envs/rvc/lib/python3.8/site-packages/fairseq/scoring/__init__.py", line 55, in <module>
    importlib.import_module("fairseq.scoring." + module)
  File "/Users/user/miniconda3/envs/rvc/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/user/miniconda3/envs/rvc/lib/python3.8/site-packages/fairseq/scoring/bleu.py", line 14, in <module>
    from fairseq.scoring.tokenizer import EvaluationTokenizer
  File "/Users/user/miniconda3/envs/rvc/lib/python3.8/site-packages/fairseq/scoring/tokenizer.py", line 8, in <module>
    import sacrebleu as sb
  File "/Users/user/miniconda3/envs/rvc/lib/python3.8/site-packages/sacrebleu/__init__.py", line 21, in <module>
    from .utils import smart_open, SACREBLEU_DIR, download_test_set  # noqa: F401
  File "/Users/user/miniconda3/envs/rvc/lib/python3.8/site-packages/sacrebleu/utils.py", line 597, in <module>
    from .dataset import DATASETS, SUBSETS, DOMAINS, COUNTRIES
  File "/Users/user/miniconda3/envs/rvc/lib/python3.8/site-packages/sacrebleu/dataset/__init__.py", line 73, in <module>
    from .wmt_xml import WMTXMLDataset
  File "/Users/user/miniconda3/envs/rvc/lib/python3.8/site-packages/sacrebleu/dataset/wmt_xml.py", line 3, in <module>
    import lxml.etree as ET
ImportError: dlopen(/Users/user/miniconda3/envs/rvc/lib/python3.8/site-packages/lxml/etree.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '_exsltDateXpathCtxtRegister'

Any idea? Thanks.

**Comment by jathoo** [comment]
I have the same issue, tried few fixes but nothing seems to fix it

**Comment by R3D347HR4Y** [comment]
Same issue
Maybe it has to do with the other AI stuff I installed so far, some using venv and some not, just in case this helps I also had Auto1111, ComfyUI and Foocus installed recently and I'm i software update late
Macbook Pro 14in M3 Pro 36GB

**Comment by dinocovelli-paramount** [comment]
Same exact issue here:
MacBook Pro, 16-inch, 2021, Apple M1 Max, 32 GB RAM

*EDIT: I can confirm that this is not an issue on my older iMac (i9 chip). The installer completed and I have the GUI open.
