### ISSUE TITLE
FFmpeg-run Error

### ISSUE THREAD

**Issue by ghost** [Mangio621/Mangio-RVC-Fork#202]
Keep getting an error every time I try to train a model using the WAV files I downloaded to use for the dataset. 

start preprocess
['trainset_preprocess_pipeline_print.py', 'C:\\Users\\mwaka\\OneDrive\\Desktop\\RVCV2\\Mangio-RVC-v23.7.0_INFER_TRAIN\\Mangio-RVC-v23.7.0\\datasets\\', '48000', '8', 'C:\\Users\\mwaka\\OneDrive\\Desktop\\RVCV2\\Mangio-RVC-v23.7.0_INFER_TRAIN\\Mangio-RVC-v23.7.0/logs/dominic-fike-1', 'False']
C:\Users\mwaka\OneDrive\Desktop\RVCV2\Mangio-RVC-v23.7.0_INFER_TRAIN\Mangio-RVC-v23.7.0\datasets\/DominicFike->Traceback (most recent call last):
  File "C:\Users\mwaka\OneDrive\Desktop\RVCV2\Mangio-RVC-v23.7.0_INFER_TRAIN\Mangio-RVC-v23.7.0\my_utils.py", line 96, in load_audio
    ffmpeg.input(file, threads=0)
  File "C:\Users\mwaka\OneDrive\Desktop\RVCV2\Mangio-RVC-v23.7.0_INFER_TRAIN\Mangio-RVC-v23.7.0\runtime\lib\site-packages\ffmpeg\_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mwaka\OneDrive\Desktop\RVCV2\Mangio-RVC-v23.7.0_INFER_TRAIN\Mangio-RVC-v23.7.0\trainset_preprocess_pipeline_print.py", line 84, in pipeline
    audio = load_audio(path, self.sr, DoFormant, Quefrency, Timbre)
  File "C:\Users\mwaka\OneDrive\Desktop\RVCV2\Mangio-RVC-v23.7.0_INFER_TRAIN\Mangio-RVC-v23.7.0\my_utils.py", line 103, in load_audio
    raise RuntimeError(f"Failed to load audio: {e}")
RuntimeError: Failed to load audio: ffmpeg error (see stderr output for detail)

end preprocess

**Comment by Nawazsherif** [comment]
Same error for me as well. Did you resolve it?

**Comment by ghost** [comment]
> Same error for me as well. Did you resolve it?

I just gave up on training using Mangio and used a diff training site for my voice models instead.

**Comment by kubinka0505** [comment]
just use applio instead
