### ISSUE TITLE
Getting some error like

### ISSUE THREAD

**Issue by chnisar515** [Mangio621/Mangio-RVC-Fork#206]
I have installed fresh copy of Mangio-RVC-v23.7.0_INFER_TRAIN.bat in windows 10 and my system specification is Intel Core i7 5500U CPU @ 2.40GHz 2.40 GHz . and 16GB RAM and 64bit windows 10 and NVIDIA GPU 940M when i run go-web.bat file i got the output in my CMD which is below.
`C:\RVC\Mangio-RVC-v23.7.0>runtime\python.exe infer-web.py --pycmd runtime\python.exe --port 7897
Found GPU NVIDIA GeForce 940M
Set fp16_run to false in 32k.json
Set fp16_run to false in 40k.json
Set fp16_run to false in 48k.json
Use Language: en_US
Running on local URL:  http://0.0.0.0:7897

To create a public link, set `share=True` in `launch()`.`

after that in my default browser i successfully see the page of (The Mangio-RVC-Fork) and there i select my audio file with full path like (C:/RVC/Mangio-RVC-v23.7.0/audios/myaudio.mp3) and all the other setting default and click on Convert Button and after few seconds wait i got Error on screen and when i check the CMD screen i got these errors which are below.
`Traceback (most recent call last):
  File "C:\RVC\Mangio-RVC-v23.7.0\my_utils.py", line 96, in load_audio
    ffmpeg.input(file, threads=0)
  File "C:\RVC\Mangio-RVC-v23.7.0\runtime\lib\site-packages\ffmpeg\_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\RVC\Mangio-RVC-v23.7.0\infer-web.py", line 292, in vc_single
    audio = load_audio(input_audio_path0, 16000, DoFormant, Quefrency, Timbre)
  File "C:\RVC\Mangio-RVC-v23.7.0\my_utils.py", line 103, in load_audio
    raise RuntimeError(f"Failed to load audio: {e}")
RuntimeError: Failed to load audio: ffmpeg error (see stderr output for detail)

Traceback (most recent call last):
  File "C:\RVC\Mangio-RVC-v23.7.0\runtime\lib\site-packages\gradio\routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\RVC\Mangio-RVC-v23.7.0\runtime\lib\site-packages\gradio\blocks.py", line 1349, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\RVC\Mangio-RVC-v23.7.0\runtime\lib\site-packages\gradio\blocks.py", line 1283, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\RVC\Mangio-RVC-v23.7.0\runtime\lib\site-packages\gradio\components.py", line 2586, in postprocess
    file_path = self.audio_to_temp_file(
  File "C:\RVC\Mangio-RVC-v23.7.0\runtime\lib\site-packages\gradio\components.py", line 360, in audio_to_temp_file
    temp_dir = Path(dir) / self.hash_bytes(data.tobytes())
AttributeError: 'NoneType' object has no attribute 'tobytes'`

so please take a look and guide me how i can solve this issue.

**Comment by taellinglin** [comment]
I think maybe there is a specific gradio version maybe...that data object doesn't have a field in it.
