### ISSUE TITLE
Dependencies Breaking Changes

### ISSUE THREAD

**Issue by RobertAgee** [Mangio621/Mangio-RVC-Fork#42]
Was working in google colab earlier today but now doesn't.  Now throws this error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 439, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1389, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1094, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 704, in wrapper
    response = f(*args, **kwargs)
  File "/content/-EVC-/GUI.py", line 1529, in save_to_wav2
    shutil.move(file_path,'./audios')
  File "/usr/lib/python3.10/shutil.py", line 813, in move
    raise Error("Destination path '%s' already exists" % real_dst)
shutil.Error: Destination path './audios/fits-ch1-00-remastermedia.mp3' already exists
Traceback (most recent call last):
  File "/content/-EVC-/GUI.py", line 158, in vc_single
    load_hubert()
  File "/content/-EVC-/GUI.py", line 100, in load_hubert
    models, _, _ = checkpoint_utils.load_model_ensemble_and_task(
  File "/usr/local/lib/python3.10/dist-packages/fairseq/checkpoint_utils.py", line 423, in load_model_ensemble_and_task
    raise IOError("Model file not found: {}".format(filename))
OSError: Model file not found: hubert_base.pt

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 439, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1392, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1326, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/usr/local/lib/python3.10/dist-packages/gradio/components/audio.py", line 329, in postprocess
    file_path = self.audio_to_temp_file(
  File "/usr/local/lib/python3.10/dist-packages/gradio/components/base.py", line 327, in audio_to_temp_file
    temp_dir = Path(dir) / self.hash_bytes(data.tobytes())
AttributeError: 'NoneType' object has no attribute 'tobytes'
```

**Comment by eggsoda** [comment]
running into the same issue!

**Comment by PatrickSLU** [comment]
![Screenshot 2023-07-24 at 5 42 05 PM](https://github.com/Mangio621/Mangio-RVC-Fork/assets/136882606/cdd7dcdf-c235-4a97-add9-5e1ad0285ac9)

This is my issue, quite similar with yours @RobertAgee  have you found any workaround so far?

**Comment by kalomaze** [comment]
Issue seems to be resolved in the latest commits.
