### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'tobytes'

### ISSUE THREAD

**Issue by Hivemind11** [Mangio621/Mangio-RVC-Fork#77]
after training a model and loading it up to test it using the model inferance tab. after choosing the model , song and the mangio crepe method then selecting convert. I get an error. the log says.

Traceback (most recent call last):
  File "D:\RVC_voice\Mangio-RVC-v23.7.0\my_utils.py", line 96, in load_audio
    ffmpeg.input(file, threads=0)
  File "D:\RVC_voice\Mangio-RVC-v23.7.0\runtime\lib\site-packages\ffmpeg\_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\RVC_voice\Mangio-RVC-v23.7.0\infer-web.py", line 292, in vc_single
    audio = load_audio(input_audio_path0, 16000, DoFormant, Quefrency, Timbre)
  File "D:\RVC_voice\Mangio-RVC-v23.7.0\my_utils.py", line 103, in load_audio
    raise RuntimeError(f"Failed to load audio: {e}")
RuntimeError: Failed to load audio: ffmpeg error (see stderr output for detail)

Traceback (most recent call last):
  File "D:\RVC_voice\Mangio-RVC-v23.7.0\runtime\lib\site-packages\gradio\routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\RVC_voice\Mangio-RVC-v23.7.0\runtime\lib\site-packages\gradio\blocks.py", line 1349, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "D:\RVC_voice\Mangio-RVC-v23.7.0\runtime\lib\site-packages\gradio\blocks.py", line 1283, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "D:\RVC_voice\Mangio-RVC-v23.7.0\runtime\lib\site-packages\gradio\components.py", line 2586, in postprocess
    file_path = self.audio_to_temp_file(
  File "D:\RVC_voice\Mangio-RVC-v23.7.0\runtime\lib\site-packages\gradio\components.py", line 360, in audio_to_temp_file
    temp_dir = Path(dir) / self.hash_bytes(data.tobytes())
AttributeError: 'NoneType' object has no attribute 'tobytes'

**Comment by Hivemind11** [comment]
I believe this is caused by a missing index file which didn't get generated in the log file.

**Comment by GH0STSecurity** [comment]
> turns out I had the wrong path to my audio folder.

Wdym, i had this problem for a very long time and couldnt fix it, i dont think i had the wrong path, also the path didnt contain spaces or special characters etc
