### ISSUE TITLE
Can't get it started. Tried with downloading the both .7z file and also installing it through a separate python env. Please help

### ISSUE THREAD

**Issue by sumeetprashant** [Mangio621/Mangio-RVC-Fork#89]
THIS IS THE ERROR WHEN .7z FILES WERE EXTRACXTED AND USED

C:\Users\Sumeet Prashant\AI\RVC 2\Mangio-RVC-v23.7.0_INFER_TRAIN\Mangio-RVC-v23.7.0>runtime\python.exe infer-web.py --pycmd runtime\python.exe --port 7897
Traceback (most recent call last):
  File "C:\Users\Sumeet Prashant\AI\RVC 2\Mangio-RVC-v23.7.0_INFER_TRAIN\Mangio-RVC-v23.7.0\infer-web.py", line 31, in <module>
    from fairseq import checkpoint_utils
  File "C:\Users\Sumeet Prashant\AI\RVC 2\Mangio-RVC-v23.7.0_INFER_TRAIN\Mangio-RVC-v23.7.0\runtime\lib\site-packages\fairseq\__init__.py", line 29, in <module>
    from fairseq.dataclass.initialize import hydra_init
  File "C:\Users\Sumeet Prashant\AI\RVC 2\Mangio-RVC-v23.7.0_INFER_TRAIN\Mangio-RVC-v23.7.0\runtime\lib\site-packages\fairseq\dataclass\initialize.py", line 8, in <module>
    from hydra.core.config_store import ConfigStore
  File "C:\Users\Sumeet Prashant\AI\RVC 2\Mangio-RVC-v23.7.0_INFER_TRAIN\Mangio-RVC-v23.7.0\runtime\lib\site-packages\hydra\__init__.py", line 5, in <module>
    from hydra import utils
  File "C:\Users\Sumeet Prashant\AI\RVC 2\Mangio-RVC-v23.7.0_INFER_TRAIN\Mangio-RVC-v23.7.0\runtime\lib\site-packages\hydra\utils.py", line 10, in <module>
    from hydra._internal.utils import (
  File "C:\Users\Sumeet Prashant\AI\RVC 2\Mangio-RVC-v23.7.0_INFER_TRAIN\Mangio-RVC-v23.7.0\runtime\lib\site-packages\hydra\_internal\utils.py", line 16, in <module>
    from omegaconf._utils import get_ref_type
ImportError: cannot import name 'get_ref_type' from 'omegaconf._utils' (C:\Users\Sumeet Prashant\AppData\Roaming\Python\Python39\site-packages\omegaconf\_utils.py)

__________________________________________________________________________________________________________________________________________

THIS IS THE ENV ERROR

Traceback (most recent call last):
  File "Z:\ai_covers\Mangio-RVC-Fork\infer-web.py", line 28, in <module>
    import gradio as gr
  File "C:\Users\Sumeet Prashant\miniconda3\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "C:\Users\Sumeet Prashant\miniconda3\lib\site-packages\gradio\components.py", line 33, in <module>
    from ffmpy import FFmpeg
ImportError: cannot import name 'FFmpeg' from 'ffmpy' (C:\Users\Sumeet Prashant\miniconda3\lib\site-packages\ffmpy\__init__.py)

**Comment by forest-cat** [comment]
Hey, i think i have the same Problem, i tried the latest release for training from huggingface, and just the repository cloned

**Comment by Error1000** [comment]
It seems that the line ``ffmpy==0.0.3`` in requirements.txt should be ``ffmpy==0.1.0``, at least that worked for me.

**Comment by forest-cat** [comment]
> It seems that the line `ffmpy==0.0.3` in requirements.txt should be `ffmpy==0.1.0`, at least that worked for me.

Yes it worked, but only with the newest version of the repository, the 7zip file from their huggingface repo does not work, because it uses `ffmpeg-python>=0.2.0` instead of `ffmpy`

**Comment by sumeetprashant** [comment]
Didn't get the same issue after changing ffmpy==0.1.0, but it's not detecting my NVIDIA GPU, so need to fix that. It says CUDA is not installed but it has been installed already.
Thanks for the help guys. :)

**Comment by sumeetprashant** [comment]
Finally this was solved after reinstalling pytorch, torchvision and torchaudio.
The requirements.text file somehow installed CPU only CUDA.

BTW it started working even with ffmpy=0.3.1
Now having a different issue after getting started
