### ISSUE TITLE
realtime-gui-new error. Can't run it

### ISSUE THREAD

**Issue by Dekosem** [Mangio621/Mangio-RVC-Fork#98]
Everytime i try to run it, it freezes and get's stuck at this. realtime-gui works good, webui works good, only realtime new fumbles.
Set fp16_run to true in 32k.json
Set fp16_run to true in 40k.json
Set fp16_run to true in 48k.json
Traceback (most recent call last):
  File "<frozen __main__>", line 3, in <module>
  File "<frozen temp>", line 43, in <module>
  File "gui_package.py", line 94, in gui_package.GUI.__init__
  File "gui_package.py", line 535, in gui_package.GUI.main_gui
  File "gui_package.py", line 472, in gui_package.GUI.main_gui.canvas_init
  File "Img_dispose.py", line 87, in Img_dispose.image_s_t
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'

**Comment by InfernalDread** [comment]
Hey, I also have this issue when trying to run the new realtime gui. I believe this issue is related to the "Pillow" installation. In the requirements.txt file, the pillow installation is set to >=9.1.1 (Pillow>=9.1.1). This means that the latest version will be downloaded, which removed the dependency that the new gui file needs to run ( the dependency was removed because it was depreciated and was replaced: https://pillow.readthedocs.io/en/stable/deprecations.html#constants). The pillow version that still has this dependency is Pillow v9.5.0 (Pillow==9.5.0). Maybe try overwriting the current pillow installation with this one and see if the error persists?

**Comment by deffcolony** [comment]
@InfernalDread 
Hi, What are exactly the steps to fix this realtime-gui-new issue? im just pretty new to python and i dont want to break stuff so i would like to have detailed steps to solve it

I have edited the requirements.txt so i replaced Pillow>=9.1.1 with Pillow>=9.5.0

**Comment by InfernalDread** [comment]
@deffcolony 

I personally haven't fixed this issue, but all that should be done after editing the requirement is installing everything normally, like what the instructions say.

**Comment by hassamc** [comment]
The way to fix this is to open a Terminal in your RVC folder and type
runtime\python.exe -m pip install pillow==9.5.0
Then it will work but the language of the Gui is in Chinese and I didn't see an option to change it.
